
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class UangPribadi extends javax.swing.JFrame {

    /**
     * Creates new form UangPribadi
     */
    public UangPribadi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LPemasukan = new javax.swing.JLabel();
        LPengeluaran = new javax.swing.JLabel();
        LSaldo = new javax.swing.JLabel();
        TFPemasukan = new javax.swing.JTextField();
        TFPengeluaran = new javax.swing.JTextField();
        BTambahPengeluaran = new javax.swing.JButton();
        BTambahPemasukan = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        Ahistori = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LPemasukan.setText("Pemasukan");

        LPengeluaran.setText("Pengeluaran");

        LSaldo.setText("Saldo");

        TFPemasukan.setText("FPemasukan");
        TFPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPemasukanActionPerformed(evt);
            }
        });

        TFPengeluaran.setText("FPengeluaran");

        BTambahPengeluaran.setText("TAMBAH");

        BTambahPemasukan.setText("TAMBAH");
        BTambahPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahPemasukanActionPerformed(evt);
            }
        });

        BReset.setText("RESET");

        jLabel1.setText("APLIKASI KEUANGAN PRIBADI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Ahistori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LSaldo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LPemasukan)
                        .addGap(51, 51, 51)
                        .addComponent(TFPemasukan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LPengeluaran)
                        .addGap(45, 45, 45)
                        .addComponent(TFPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BReset, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTambahPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTambahPemasukan, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPemasukan)
                    .addComponent(TFPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTambahPemasukan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPengeluaran)
                    .addComponent(TFPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTambahPengeluaran))
                .addGap(21, 21, 21)
                .addComponent(LSaldo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BReset))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ahistori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPemasukanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TFPemasukanActionPerformed

    private void BTambahPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahPemasukanActionPerformed
        // TODO add your handling code here:
        /* Menambahkan ActionListener untuk tombol Tambah Pemasukan
        */
        BTambahPemasukan.addActionListener((ActionEvent e) -> {
            double Pemasukan =Double.parseDouble(TFPemasukan.getText());
            String saldo = null;
            String pemasukan = null;
            saldo += pemasukan;
            String histori = "Pemasukan: Rp " + pemasukan + "\n";
            Ahistori.append(histori);
            LSaldo.setText("Saldo: Rp " + saldo);
            
            TFPemasukan.setText("");
        });
    }//GEN-LAST:event_BTambahPemasukanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UangPribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UangPribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UangPribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UangPribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UangPribadi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea Ahistori;
    private javax.swing.JButton BReset;
    private javax.swing.JButton BTambahPemasukan;
    private javax.swing.JButton BTambahPengeluaran;
    private javax.swing.JLabel LPemasukan;
    private javax.swing.JLabel LPengeluaran;
    private javax.swing.JLabel LSaldo;
    private javax.swing.JTextField TFPemasukan;
    private javax.swing.JTextField TFPengeluaran;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
